version: "3.2"
services:
  app:
    # you can override CMD from Dockerfile
    command: node app.js
    # load .env file entires as env variables in container
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # define port inside the container (target) and port exposed to
      # the outside world (published); if not specified in .env
      # file, default values will be used (defined after :-)
      - published: ${DOCKER_EXPOSE_APP_PORT:-3000}
        target: ${APP_PORT:-3000}
      - published: ${DOCKER_EXPOSE_APP_DEBUGGING_PORT:-9229}
        target: ${APP_DEBUGGING_PORT:-9229}
    volumes:
      # mount this app under /app in container
      - .:/app/
    depends_on:
      - db
  db: # inside containers, this becomes you db hostname
    image: postgres:latest # use fixed version in a real-world scenario
    ports:
      - published: ${DOCKER_EXPOSE_DB_PORT:-5432}
        target: ${DB_PORT:-5432}
    environment:
      # if want to change these settings after initial build you will
      # have to remove ./data directory or do it manually in pg
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      # db files will be stored in root directory under ./data/
      - ./data/db:/var/lib/postgresql/data
