version: "3.2"
services:
  app:
    command: node app.js
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - published: ${DOCKER_EXPOSE_APP_PORT:-3000}
        target: ${APP_PORT:-3000}
      - published: ${DOCKER_EXPOSE_APP_DEBUGGING_PORT:-9229}
        target: ${APP_DEBUGGING_PORT:-9229}
    volumes:
      - .:/app/
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - published: ${DOCKER_EXPOSE_DB_PORT:-5432}
        target: ${DB_PORT:-5432}
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./data/db:/var/lib/postgresql/data
